import Home from "./Home";
import About from "./About";
import Login from "./Login";
import Signup from "./Signup";
import Product from "./Product";
import UserPanel from "./UserPanel";
import PageNotFound from "./PageNotFound";
import Cart from "./Cart";
import Checkout from "./Checkout";
export { Home, About, Login, Signup, Product, UserPanel, Cart, Checkout };
